ansible-collections/overview

README.rst

See title.
- Bugfix Pull Request
Docs.
N/A

Fixed typo in Developing Collections link

---

README.rst

Docs: More details on running from devel

---

README.rst

Minor typo and formatting fixes

---

README.rst

moving pugins across collections
plugins

README.rst  moving plugins 

---

status.rst

Big ticket items (link to PR/proposal)

WIP Project Status

---

status.rst

Add some detail on the top priorities for documentation in the collections world for docs.ansible.com.
docs.ansible.com
```paste below
```

Track top open documentation issues

---

README.rst

Fixes indentation of an unsorted list
Docs Pull Request

fix visualization

---

collection_requirements.rst

missing backtick
documentation

missing backtick

---

collection_requirements.rst

added pointer to migrating content

---

README.rst

point to migrating content section in  docs

---

collection_requirements.rst

Updates #90 with information on versioning and deprecation.
Should be redirected to master once #90 is merged; I'm keeping it directed at #90's branch for now so it's easier to see the differences.
CC @gundalow @abadger @acozine @samccann

Add details on versioning and deprecation

---

tmp-announcement.md

Wordsmiths the collection announcement for Ansible 2.10, including specific wording discussed in today's Community WG meeting and several other changes.
Announcement

streamline the announcement

---

collection_requirements.rst

collection_requirements.rst: add naming recommendations

collection_requirements.rst: add naming recommendations

---

collection_requirements.rst

collection_requirements.rst: fix formatting

collection_requirements.rst: fix formatting

---

collection_requirements.rst

collection_requirements.rst: change part related to naming

collection_requirements.rst: change part related to naming

---

collection_requirements.rst

Fixes #106.
CC @bmillemathias  (can't request a review from you :) )

Clarify requirements

---

collection_requirements.rst

collections_requirements.rst: add reference to submitting namespace
```collections_requirements.rst```

collections_requirements.rst: add reference to submitting namespace

---

collection_requirements.rst

Add note to check docsite on FQCNs after moving modules/plugins to collection
`collection_requirements.rst`

Add note to check docsite on FQCNs after moving modules/plugins to collection

---

README.rst

Fixes broken links in the README

Fixed broken links

---

README.rst

fixed indentation / formatting of `ansible-base` in the `Terminology` section
README.rst

fixed indentation / formatting

---

collection_requirements.rst

Add a note about adding new collections to ansible-build-data.
`collection_requirements.rst`

Add a note about adding new collections to ansible-build-data

---

collection_requirements.rst

Related to https://github.com/ansible/community/issues/539#issuecomment-729954216
Add the section to the checklist: List of requirements for collections to be included in Ansible
I know that it hasn't been discussed yet. However **we should start from something** and, in my opinion, there are obvious things listed in the PR. Anyway, i can correct / remove something if it's too premature now.
Alternatively, we could start listing the requirements in a separate file not mixing everything in one place.
Note: i put links to the doc pages which is in devel because they are actually latest, can be important in this case.
`collection_requirements.rst`

Add the section to the checklist: List of requirements for collections to be included in Ansible

---

collection_requirements.rst

Update CI testing that:
* Sanity tests must pass
* Initial rules around use of ignores.txt
- Bugfix Pull Request
- New Module Pull Request
```paste below
```

Must change changes to the checklist criteria

---

collection_requirements.rst

- Bugfix Pull Request
- New Module Pull Request
```paste below
```

documentation of upstream contribution terms requirement

---

collection_requirements.rst

collection_requirements: Fix formatting
`collection_requirements.rst`

collection_requirements: Fix formatting

---

collection_requirements.rst

The substantive changes in
https://github.com/ansible-collections/overview/pull/132/commits/b4c59b2f96338dab54e7bef0f400d678f9fc12c4
were not approved in the meeting.
However, the checklist as a whole was approved in the next meeting.
This leaves the text in this PR in an odd situation where it might be
approved or might not.  This PR is not necessarily the proposal; tather
the change needs to be discussed, possibly a new proposal needs to be
created, and it needs to be voted approved at the next meeting.
```paste below
```

Need approval of the CI changes

---

collection_checklist.md
collection_requirements.rst

Based on the discussion in today's community meeting.

Extend collection requirements

---

collection_checklist.md
collection_requirements.rst

As discussed at this week's community meeting (https://meetbot.fedoraproject.org/ansible-community/2021-01-13/ansible_community_meeting.2021-01-13-19.00.html).
collection_checklist.md

Update collection requirements

---

collection_checklist.md
collection_requirements.rst

Write up of the plugin type collection criteria which was approved at the Community IRC Meeting of 2021-01-20.

Add a requirement that plugins must be one of the recognized types

---

collection_checklist.md

collection_checklist: fix formatting

collection_checklist: fix formatting

---

collection_checklist.md
collection_requirements.rst

This was voted on in [today's community meeting](https://github.com/ansible/community/issues/539#issuecomment-772822939).
collection requirements

Requirements: collections must have public SCM repos, and releases must be tagged in them

---

collection_checklist.md
collection_requirements.rst

* Needed to have the new python guidelines section added to know what
the link target would be for the checklist.
* Also fix formatting of the guidelines: it's rst , not md.
```paste below
```

Fix link target and formatting.

---

collection_checklist.md

collection_checklist: improve

---

collection_requirements.rst

https://github.com/ansible/community/issues/539#issuecomment-801413570

Add note about naming on different platforms

---

collection_requirements.rst

Update collection requirements with link to [inclusion criteria checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md).

Updated collection_requirements.rst with inclusion criteria link

---

collection_checklist.md
collection_requirements.rst

Add _info / _facts module related notes

Add _info / _facts module related notes

---

README.rst
collection_requirements.rst

Change Freenode to Libera.chat

Change Freenode to Libera.chat

---

collection_requirements.rst

collection_requirements: update Versioning section

collection_requirements: update Versioning section

---

README.rst

Improvements to README

---

collection_checklist.md

Fix checklist

---

collection_requirements.rst

Follow up on #199.
Clarifies the distinction between internal and public resources in a collection.
Collections.

wordsmiths the externa/internal thing a bit

---

collection_checklist.md

collection_checklist: Add clarifications for not experienced collection reviewers

collection_checklist: Add clarifications for collection reviewers

---

collection_checklist.md

collection_checklist.md: Fix formatting

collection_checklist.md: Fix formatting

---

.github/ISSUE_TEMPLATE/bug_report.md
README.rst
collection_requirements.rst

Just a bunch of whitespace normalization

all the whitespace changes

---

collection_requirements.rst

See https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management vs https://github.com/gotmax23/overview/blob/scmfixup/collection_requirements.rst#repository-management

Repository management: Fix formatting

---

collection_checklist.md
collection_requirements.rst

As was discussed in https://github.com/ansible-community/community-topics/issues/152#issuecomment-1293260128

Collection requirements: mention idepmotency explicitly

---

collection_checklist.md

collection_checklist: add clarification about version_added use
I don't think any vote is needed as this info is present in https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#documentation-1

collection_checklist: add clarification about version_added use

---

README.rst

One `^` is missing so parsing is not correctly done in README
```paste below
```

Fix typo in subsubsections

---

collection_checklist.md

As were discovered in https://github.com/ansible/ansible-documentation/pull/1422#discussion_r1598720711

Remove nomust from collection checklist

---

collection_checklist.md

Fix collection_checklist.md link

Fix collection_checklist.md link
