ansible-collections/overview

README.md, README.rst
Community docs for Collections.
My hope is every time someone asks a question a PRs is raised to update this document.
* This isn't in the main docsite (docs.ansible.com) so we can iterate faster, especially between now and 2.10 being released.
Review welcome:
* Is this clear
* What other FAQ entries could be added
=> Docs: Collections overview

README.rst, status.rst
- Bugfix Pull Request
- New Module Pull Request
```paste below
```
=> WIP Update README.rst

collection_requirements.rst
Requirements for Collections to be included in Ansible
This is currently in bullet point form, we can expand over time.
This could live elsewhere, though I realise it hasn't been captured at all so far.
Commits to update wording here are welcome.
=> Collection checklist

README.rst
I haven't found Ansible Collection Checklist on the doc site. Seems that it's not there yet.
Until that, would be good to have a reference to the file in README. Later we could change it to a corresponding doc page.
=> [WIP] README: Add a reference to Ansible Collection Checklist

.github/workflows/rstlint.yml, status.rst
Validate RST files
Add basic validation as occasionally GitHub was only showing the raw RST text due to errors such as incorrect headings.
=> Validate RST files

collection_requirements.rst
The current ansible module_utils are actually under the BSD-2-clause license, not the BSD-3-clause license.
```paste below
```
=> BSD License for module_utils should be 2 clause

collection_requirements.rst
* Collections MUST be on Galaxy
* Collections MUST have a `README.md`
=> MUST be published to Galaxy + README.md

collection_requirements.rst
Suggestion of unacceptable entries for ignore files, per comment:
https://github.com/ansible-collections/overview/pull/132\#discussion_r539635888
As of today (Dec 13, 2020), the rank of ignore entries' types is (for ``tests/sanity/ignore-2.10.txt``):
```
$ ../sort-ignores tests/sanity/ignore-2.10.txt
129 validate-modules:parameter-list-no-elements
87 validate-modules:parameter-type-not-in-doc
84 validate-modules:doc-missing-type
53 validate-modules:undocumented-parameter
27 pylint:blacklisted-name
23 validate-modules:return-syntax-error
22 validate-modules:invalid-ansiblemodule-schema
21 validate-modules:doc-default-does-not-match-spec
11 validate-modules:parameter-state-invalid-choice
11 validate-modules:parameter-invalid
7 …
```
=> List of unacceptable values for new entries in ignore files

collection_requirements.rst
The change to requiring Ansible's Code of Conduct wasn't approved:
https://github.com/ansible-collections/overview/pull/132/commits/e574a2563e06a4fa6e75587760564ab8de11988e
However, the checklist in its entirety was approved.
This puts this bit of text in an odd situation where it might be
approved or might not.  This PR is not necessarily the proposal; rather
the change needs to be discussed, possible a new prposal created, and
voted on at the next meeting. Note that both tadeboro and abadger1999
dissent with the change from "Requires a CoC" to "Requires the Ansible
CoC".
```paste below
```
=> Need approval for the Code of Conduct changes

collection_requirements.rst
Make it clearer that repo management subsection is only about gh.com/ansible-collections.
=> The repository management subsection is for gh.com/ansible-collections

collection_checklist.md, collection_requirements.rst
Polished policy for limiting plugin types.
```paste below
```
=> Limiting plugin types 2

collection_requirements.rst
This makes it explicit that DOCUMENTATION and EXAMPLES are required
while RETURN is optional.
Otherwise the content is largely the same but re-organized for clarity.
This was an action item from a community meeting:
https://github.com/ansible/community/issues/539#issuecomment-759732766
=> Improve clarity of the documentation requirements

collection_requirements.rst
Now that ansible/ansible#73508 landed in devel's sanity tests, it is mandatory that collections mark false positives with `no_log=False` in the argument spec and **NOT** simply ignore `no-log-needed` for a module file.
=> Collection guidelines: disallow validate-modules:no-log-needed ignore.txt entries

collection_checklist.md, collection_requirements.rst
- Added new policy regarding python compatibility for Collections.
=> New Policy Regarding Python Compatibility for Collections

collection_checklist.md, collection_requirements.rst
Allow modules and module_utils to use licenses that are compatible with
the GPLv3+ rather than restricting them to only the GPLv3+.
This is to address the issue raised here: https://github.com/ansible-community/community-topics/issues/2
(Allowing a collection with modules licensed under Apache v2)
t
=> Expand the licenses allowed in collections

collection_checklist.md, collection_requirements.rst
Expand checklist and clarify requirements
=> Expand checklist and clarify requirements

collection_checklist.md, collection_requirements.rst
Implements https://github.com/ansible-community/community-topics/issues/77. Once that is approved (and word-smithing has been done here), this can be merged.
collection requirements
=> Add new rule on files outside of meta/, plugins/, roles/, and playbooks/

README.rst
fixes: #203
2.10 is now long since released, there's no need for an FAQ asking when the big collections split will happen.
README.md
=> Remove FAQ asking when the collections changes will land

removal_from_ansible.rst
I wrote this up based on the discussion we had at today's community meeting. The aim of this PR is to have some basic rules on which collections can be removed so we can vote on them soon and establish them. The aim is **not** to have a complete list of rules. I expect we will have more discussions and additional situations added to this document in follow-up PRs.
The two processes described here are modelled after two explicit examples:
1. community.kubevirt is currently broken and does not work as inclued in Ansible 5, since it requires community.kubernetes < 2.0.0, while Ansible 5 includes community.kubernetes >= 2.0.0. Adjusting the collection to community.kubernetes >= 2.0.0 or kubernetes.core >= 2.0.0 have been unsuccessful and stagnated …
=> Describe how collections can be removed from the Ansible package

.github/workflows/rstlint.yml, collection_checklist.md, collection_requirements.rst
Relates to https://github.com/ansible-collections/ansible-inclusion/discussions/44#discussioncomment-2889787.
As integration/unit tests are optional anyway and it can be expensive to run them against release commits, i suggest making their run optional.
=> Change requirements related to running tests against release commit

collection_requirements.rst
Right now, the rules state that *"[a]ll other code must be under the GPL-3.0-or-later"*. From the explanation it is clear that this sentence is about all other code in plugins/, but it is not formulated that way.
The current formulation implies for example that all unit tests, helper scripts, or code files included in roles, playbooks, or integration tests must be licensed under GPLv3+. Especially for unit tests this can be problematic; for example community.docker now vendors some code from Docker SDK for Python (Apache 2.0 licensed) including unit tests for that code. The unit tests are also licensed under Apache 2.0, but this would violate a strict interpretation of the inclusion requirements.
This PR proposes an improved formulation that makes it clear that other code **outside …
=> Make it clear that code outside plugins/ can have other free software licenses as well

collection_checklist.md, collection_requirements.rst
We require that all collections [MUST have a public SCM repository](https://github.com/ansible-collections/overview/blob/24343d3d7723adaf911f2fcc3a69d02bb713fa2a/collection_requirements.rst#repository-management).
Actually, most people will use git nowadays but in theory, they could use any obscure SCM as long as the repo is publicly available.
This means that we might have to deal with a SCM we don't know and our tooling doesn't support. Therefor, I suggest requiring git instead of generic SCM repositories.
collection_checklist.md
https://github.com/ansible-community/community-topics/issues/148#issuecomment-1277828717
cc @felixfontein
=> Clarify SCM and release requirements

removal_from_ansible.rst
removal_from_ansible.rst: add paragraph about removal collections violating the requirements
to explicitly cover cases that don't belong to unmaintained/broken collections
related discussion https://github.com/ansible-community/community-topics/issues/150
=> removal_from_ansible.rst: add paragraph about removal collections violating the requirements

collection_checklist.md
collection_checklist.md: update
=> collection_checklist.md: update
